print("Program starting.\n")
word=input("Insert a closed compound word: ")
print(f"The word you inserted is '{word}' and in reverse it is'{word[::-1]}'.")
length=len(word)
print(f"The inserted word length is {length}")
print(f"Last character is '{word[-1]}'"'\n')
print("Take substring from the inserted word by inserting...")
start=int(input("1) Starting point: "))
end=int(input("2) Ending point: "))
step=int(input("3) Step size: "))
print(f"\nThe word '{word}' sliced to the defined substring is '{word[start:end:step]}'.\n")
print("Program ending.")